In [16]:
#dependencies

import pretty_midi
import os
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras
from keras.utils import to_categorical


In [7]:
# Set directory path where MIDI files are located
midi_dir = "C:/Users/simas/Downloads/Midis by Alawais/midi dataset/"

# Create list of MIDI file paths
files = []
for file in os.listdir(midi_dir):
    if file.endswith(".mid"):
        files.append(os.path.join(midi_dir, file))

In [8]:
print(files)

['C:/Users/simas/Downloads/Midis by Alawais/midi dataset/0.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/1.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/10.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/100.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/101.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/102.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/103.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/104.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/105.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/106.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/107.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/108.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/109.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/11.mid', 'C:/Users/simas/Downloads/Midis by Alawais/midi dataset/110.mid', 'C:/Users/simas

In [9]:
# Load MIDI files into memory
midi_data = []
for file in files:
    midi_data.append(pretty_midi.PrettyMIDI(file))

In [10]:
print(midi_data)

[<pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA241160>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CA7B02940>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA21CFD0>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA21A040>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA219250>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA188A60>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA21D400>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA241190>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019C9D0765B0>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA23F430>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA219C10>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA21CDC0>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA219D90>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA23F310>, <pretty_midi.pretty_midi.PrettyMIDI object at 0x0000019CAA33D

In [11]:
# Extract MIDI messages from MIDI files
messages = []
for midi in midi_data:
    for instrument in midi.instruments:
        for note in instrument.notes:
            message = (note.pitch, note.velocity, note.start)
            messages.append(message)

messages = np.array(messages)

In [12]:
print(messages)

[[ 69.       127.         0.      ]
 [ 60.       127.         0.      ]
 [ 53.       127.         0.      ]
 ...
 [ 65.       127.        11.090898]
 [ 67.       127.        11.090898]
 [ 91.       127.        11.454534]]


In [13]:
sequence_length = 32

sequences = []
for i in range(len(messages) - sequence_length):
    sequence = messages[i:i + sequence_length]
    sequences.append(sequence)
    
sequences = np.array(sequences)

In [ ]:
print(sequences)

In [17]:
encoded_sequences = to_categorical(sequences)

In [19]:
# Save the encoded sequences to a .npy file
np.save("encoded_sequences.npy", encoded_sequences)

In [20]:
print(os.getcwd())

c:\Users\simas\AppData\Local\Programs\Microsoft VS Code
